# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 580996326cde4c58f86d4c43fbc8a3d4645e7b903ccc12124b01260840cea1852bbab8554d918c8840d995f18aff85bb52370b48d9cd6c89969303457a88790f

test:
  secret_key_base: 9d0095c0095e165e0695c3da684c5325f17436f1a2d1148b4720ca5138a0389b4a73e21988c84e04ad89557bba37712cca40c5f389cf2a5536852e46a8f2fa9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
