# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8a1e7eae9bc4b72aca9a44f9cbdba418d2cf36e5c1fea9eb736b7ab586097a67c361ac4b3fc95a6a5966e40c195c1a45ab789e762cb512747922785b49e8ee7

test:
  secret_key_base: e586be0a05c5b1e1563cc877a9783a63ee6d3c18f36b78c2380457b723a9dd6f1f34891a254462c66ef84b5a1c706f1c9bc7e9c4ac35b23fe8e7b96b4a62489c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
